### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by gaurang2001** [IEEE-NITK/ieee-website-jekyll#1]
Currently, all of the achievements are on the main site in HTML format. We need to move all of the content to JSON files.
- [x] Create a new page called `achieve.html`.
- [x] Create a new JSON file called `achievements.json`. Load some achievements from the main site into it. It is better to structure the JSON into four major segments according to the headings on the website page.
- [x] Use the `default` layout and generate data from the `achievements.json` file.

Refer to [https://ieee.nitk.ac.in/achieve.html](https://ieee.nitk.ac.in/achieve.html)

**Comment by Shreeranjita1222** [comment]
I'll take this up?
