### ISSUE TITLE
Publications

### ISSUE THREAD

**Issue by gaurang2001** [IEEE-NITK/ieee-website-jekyll#2]
Currently, all of the publications on the main site are in HTML format. We need to move all of the content to JSON files.
- [x] Create a new page called `publications.html`.
- [x] Create a new JSON file called `publications.json`. Load some publications from the main site into it.
- [x] Use the `default` layout and generate data from the `publications.json` file.

Refer to [https://ieee.nitk.ac.in/publications.html](https://ieee.nitk.ac.in/publications.html)

**Comment by Shashankhs17** [comment]
I am shashank H S and I would like to take this issue.
Please assign it to me.
