### ISSUE TITLE
SIG Pages

### ISSUE THREAD

**Issue by gaurang2001** [IEEE-NITK/ieee-website-jekyll#3]
Each of the SIG pages has a list of projects, which overflows and doesn't really look organised.
- [ ] Use the `default` layout.
- [ ] Migrate all old projects (before the age of virtual expos) to a `<sig>_projects.json` file. 
- [ ] Load projects into the page in a year-wise division of tabs.
- [ ] Add links to virtual expo websites for virtual expo projects.

**Comment by Nitin-T-Singh** [comment]
I am Nitin kumar,can you please assign this issue to me.

**Comment by gaurang2001** [comment]
@Shashankhs17 Also make sure Awards and Publications pages are synced.
