### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by gaurang2001** [IEEE-NITK/ieee-website-jekyll#4]
- [ ] Instead of the Events section on the Home page have a section for recent blogs. This can be achieved by an AJAX request to [https://ieee.nitk.ac.in/blog/search.json](https://ieee.nitk.ac.in/blog/search.json) and pick out the three latest blogs from the JSON result.

**Note:** This is more of an AJAX task than Jekyll.

**Comment by shama-shankar** [comment]
I am Shama and I would like to take this up.
