### ISSUE TITLE
Events Page

### ISSUE THREAD

**Issue by gaurang2001** [IEEE-NITK/ieee-website-jekyll#5]
- [x] Create a new `events.html` page and move all events to that page from the home page.
- [x] We currently use Javascript to render events, translate it all to Jekyll (Liquid).
- [x] All event titles should be displayed in cards along with a "Read More" button that opens up a modal.
- [ ] Sample JSON files for the events are provided within the `_data` folder.

**Comment by sumukh7039** [comment]
I am Sumukh C P and I would like to take this issue.
