### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by gaurang2001** [IEEE-NITK/ieee-website-jekyll#6]
- [x] Faculties can be hard-coded, just like the current implementation.
- [x] Executive member details should be read from the `team.json` file and displayed just like the current implementation.
- [x] If possible, you're free to divide the members into five tabs for five sections - Core, Compsoc Members, Diode Members, Piston Members, Alumni

**Comment by Shashankhs17** [comment]
I would like to work on this. Please assign it to me.
